version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    init: true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - PUBLIC_API_BASE_URL=http://localhost:8081
