apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    app.kubernetes.io/name: random-generator-webapp
    app.kubernetes.io/component: frontend
data:
  PUBLIC_API_BASE_URL: "http://localhost:32081"

