apiVersion: v1
kind: Service
metadata:
  name: random-generator-webapp-frontend-service
  labels:
    app.kubernetes.io/name: random-generator-webapp
    app.kubernetes.io/component: frontend
spec:
  selector:
    app.kubernetes.io/name: random-generator-webapp
    app.kubernetes.io/component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32080
  type: NodePort
