apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-generator-webapp-backend
  labels:
    app.kubernetes.io/name: random-generator-webapp
    app.kubernetes.io/component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: random-generator-webapp
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: random-generator-webapp
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: backend
        image: quay.io/alcosta/random-generator-webapp/backend:latest
        ports:
        - containerPort: 8081

