apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-generator-webapp-frontend
  labels:
    app.kubernetes.io/name: random-generator-webapp
    app.kubernetes.io/component: frontend
  annotations:
    package-operator.run/phase: deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: random-generator-webapp
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: random-generator-webapp
        app.kubernetes.io/component: frontend
    spec:
      shareProcessNamespace: true
      containers:
        - name: frontend
          image: quay.io/alcosta/random-generator-webapp/frontend:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: frontend-config
