apiVersion: manifests.package-operator.run/v1alpha1
kind: PackageManifest
metadata:
  name: random-generator-webapp-frontend
spec:
  scopes:
    - Namespaced
  phases:
    - name: deploy
  availabilityProbes:
    - probes:
        - condition:
            type: Available
            status: "True"
        - fieldsEqual:
            fieldA: .status.updatedReplicas
            fieldB: .status.replicas
      selector:
        kind:
          group: apps
          kind: Deployment
  config:
    openAPIV3Schema:
      properties:
        apiBaseUrl:
          description: API base URL to contact the backend
          type: string
          default: "http://localhost:8081"
      type: object
