apiVersion: manifests.package-operator.run/v1alpha1
kind: PackageManifest
metadata:
  name: random-generator-webapp-backend
spec:
  scopes:
    - Namespaced
  phases:
    - name: deploy
  availabilityProbes:
    - probes:
        - condition:
            type: Available
            status: "True"
        - fieldsEqual:
            fieldA: .status.updatedReplicas
            fieldB: .status.replicas
      selector:
        kind:
          group: apps
          kind: Deployment
